apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ealves-playground
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ealves96/Inception-of-things
    targetRevision: HEAD
    path: p3/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ealves-playground
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ealves-playground
  template:
    metadata:
      labels:
        app: ealves-playground
    spec:
      containers:
      - name: ealves-playground
        # To change versions, modify this tag between v1 and v2
        image: ealves42/playground:v1
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: ealves-playground
  namespace: dev
spec:
  selector:
    app: ealves-playground
  ports:
  - port: 8888
    targetPort: 8888
  type: NodePort
---
