apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.argoproj.io
spec:
  group: argoproj.io
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    shortNames:
    - app
    - apps
    singular: application
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          spec:
            type: object
            required:
            - destination
            - project
            - source
            properties:
              destination:
                type: object
                required:
                - server
                properties:
                  namespace:
                    type: string
                  server:
                    type: string
              project:
                type: string
              source:
                type: object
                required:
                - repoURL
                properties:
                  chart:
                    type: string
                  helm:
                    type: object
                    properties:
                      releaseName:
                        type: string
                  path:
                    type: string
                  repoURL:
                    type: string
                  targetRevision:
                    type: string
              syncPolicy:
                type: object
                properties:
                  automated:
                    type: object
                    properties:
                      prune:
                        type: boolean
                      selfHeal:
                        type: boolean
                  syncOptions:
                    type: array
                    items:
                      type: string
    served: true
    storage: true
    subresources:
      status: {} 